config/routes.rb
ClinicasLibres::Application.routes.draw do
  devise_for :users,:skip => :registrations
  match 'agenda', to: 'agenda#index', as: 'agenda', via: 'get'
  
  
  match '/users', to: 'users#index', as:'users', via: 'get'
  match '/users/*path', to: 'users#index', via: 'get'
  namespace :api, defaults: {format: 'json'} do
    resources :eventos, except: [:update,:new,:edit,:show]
    resources :doctors, except: [:update,:new,:edit]
    resources :users, except: [:new,:edit] do
      match '/reset_password', to: 'users#reset_password', as: "reset_password", via: 'post'
    end
    scope '/buscar' do
    	match '/pacientes',to: 'pacientes#buscar_pacientes',as:'buscar_pacientes', via: 'get'
    end
  end

  root "principal#index"
end

app/views/layouts/web/header/_mainbar.html.erb
 <div class="mainbar">
  <div class="container">
    <button type="button" class="btn mainbar-toggle" data-toggle="collapse" data-target=".mainbar-collapse">
      <i class="fa fa-bars"></i>
    </button>
    <div class="mainbar-collapse collapse">
      <ul class="nav navbar-nav mainbar-nav">
        <%if controller_name == 'principal'%>
          <li class="active">
        <%else%>
          <li>
        <%end%>           
          <%= link_to root_path do%>
            <i class="fa fa-dashboard"></i>
            Dashboard
          <%end%>
        </li>
        <%if controller_name == 'agenda'%>
          <li class="active">
        <%else%>
          <li>
        <%end%>
          <%= link_to agenda_path do%>
            <i class="fa fa-calendar"></i>
            Agenda
          <%end%>
        </li>
        <%if controller_name == 'users'%>
          <li class="active">
        <%else%>
          <li>
        <%end%>
          <%= link_to users_path do%>
            <i class="fa fa-user"></i>
            Usuarios
          <%end%>
        </li>
      </ul>
    </div> <!-- /.navbar-collapse -->
  </div> <!-- /.container --> 
</div> <!-- /.mainbar -->

app/views/layouts/web/header/_navbar.html.erb
<div class="navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <i class="fa fa-cogs"></i>
      </button>
      <a class="navbar-brand navbar-brand-image" href="/">
        <img src="http://preview.jumpstartthemes.com/target-admin/img/logo.png" alt="Site Logo">
      </a>
    </div> <!-- /.navbar-header -->
    <div class="navbar-collapse collapse">
      <%= render 'layouts/web/header/navbar/left'%>
      <%= render 'layouts/web/header/navbar/right'%>
    </div> <!--/.navbar-collapse -->
  </div> <!-- /.container -->
</div> <!-- /.navbar -->