config/routes.rb
ClinicasLibres::Application.routes.draw do
  devise_for :users,:skip => :registrations
  match 'agenda', to: 'agenda#index', as: 'agenda', via: 'get'
  
  
  match '/users', to: 'users#index', as:'users', via: 'get'
  match '/users/*path', to: 'users#index', via: 'get'
  namespace :api, defaults: {format: 'json'} do
    resources :eventos, except: [:update,:new,:edit,:show]
    resources :doctors, except: [:update,:new,:edit]
    resources :users, except: [:new,:edit] do
      match '/reset_password', to: 'users#reset_password', as: "reset_password", via: 'post'
    end
    scope '/buscar' do
    	match '/pacientes',to: 'pacientes#buscar_pacientes',as:'buscar_pacientes', via: 'get'
    end
  end

  root "principal#index"
end

app/views/layouts/web/header/navbar/_left.html.erb
<ul class="nav navbar-nav noticebar navbar-left">
  <li class="dropdown">
    <a href="./page-notifications.html" class="dropdown-toggle" data-toggle="dropdown">
      <i class="fa fa-bell"></i>
      <span class="navbar-visible-collapsed">&nbsp;Notifications&nbsp;</span>
      <span class="badge">3</span>
    </a>
    <ul class="dropdown-menu noticebar-menu" role="menu">
      <li class="nav-header">
        <div class="pull-left">
          Notifications
        </div>
        <div class="pull-right">
          <a href="javascript:;">Mark as Read</a>
        </div>
      </li>
      <li>
        <a href="./page-notifications.html" class="noticebar-item">
          <span class="noticebar-item-image">
            <i class="fa fa-cloud-upload text-success"></i>
          </span>
          <span class="noticebar-item-body">
            <strong class="noticebar-item-title">Templates Synced</strong>
            <span class="noticebar-item-text">20 Templates have been synced to the Mashon Demo instance.</span>
            <span class="noticebar-item-time"><i class="fa fa-clock-o"></i> 12 minutes ago</span>
          </span>
        </a>
      </li>
      <li>
        <a href="./page-notifications.html" class="noticebar-item">
          <span class="noticebar-item-image">
            <i class="fa fa-ban text-danger"></i>
          </span>
          <span class="noticebar-item-body">
            <strong class="noticebar-item-title">Sync Error</strong>
            <span class="noticebar-item-text">5 Designs have been failed to be synced to the Mashon Demo instance.</span>
            <span class="noticebar-item-time"><i class="fa fa-clock-o"></i> 20 minutes ago</span>
          </span>
        </a>
      </li>
      <li class="noticebar-menu-view-all">
        <a href="./page-notifications.html">View All Notifications</a>
      </li>
    </ul>
  </li>
</ul>

app/views/layouts/web/header/navbar/_right.html.erb
<ul class="nav navbar-nav navbar-right"> 
  <li>
    <a href="javascript:;">Acerca de</a>
  </li>        
  <li>
    <a href="javascript:;">Recursos</a>
  </li>
  <% if user_signed_in?%>    
  <li class="dropdown navbar-profile">
    <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;">
      <img src="http://preview.jumpstartthemes.com/target-admin/img/avatars/avatar-1-xs.jpg" class="navbar-profile-avatar" alt="">     
      <%= current_user.email %>
    </a>
    <ul class="dropdown-menu" role="menu">
      <li>
        <a href="./page-profile.html">
          <i class="fa fa-user"></i> 
          &nbsp;&nbsp;My Profile
        </a>
      </li>
      <li>
        <a href="./page-pricing.html">
          <i class="fa fa-dollar"></i> 
          &nbsp;&nbsp;Plans &amp; Billing
        </a>
      </li>
      <li>
        <a href="./page-settings.html">
          <i class="fa fa-cogs"></i> 
          &nbsp;&nbsp;Settings
        </a>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        
      </li>
    </ul>
  </li> 
  <%else%>
  <li>
    <%= link_to "Sign in", new_session_path(resource_name) %>
  </li> 
  <%end%>
</ul>   